server_location       = "westus2"
tftrain_akrg          = "tftrain_akrg"
resource_prefix       = "testtf-server"
server_address_space  = "1.0.0.0/22"
server_address_prefix = "1.0.1.0/24"
server_name           = "testtf-01"
environment           = "development"